  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SnYv-NUM3n2DAL-077lkrDxYsFhaE_Y',
    appId: '1:958917211661:web:425f05da4b1f2de8a74744',
    messagingSenderId: '958917211661',
    projectId: 'consulto-3bd7b',
    authDomain: 'consulto-3bd7b.firebaseapp.com',
    storageBucket: 'consulto-3bd7b.firebasestorage.app',
    measurementId: 'G-DBSD5WKTWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSLEpeB4lPLDKg3c9PDgQ2qE94YecHBg',
    appId: '1:958917211661:android:d80231a64b5898d3a74744',
    messagingSenderId: '958917211661',
    projectId: 'consulto-3bd7b',
    storageBucket: 'consulto-3bd7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuAxvFDkdrPjPqBx-GvN8MYLYB1DwBHKA',
    appId: '1:958917211661:ios:a2c2d707e9706152a74744',
    messagingSenderId: '958917211661',
    projectId: 'consulto-3bd7b',
    storageBucket: 'consulto-3bd7b.firebasestorage.app',
    iosBundleId: 'com.example.consulto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuAxvFDkdrPjPqBx-GvN8MYLYB1DwBHKA',
    appId: '1:958917211661:ios:a2c2d707e9706152a74744',
    messagingSenderId: '958917211661',
    projectId: 'consulto-3bd7b',
    storageBucket: 'consulto-3bd7b.firebasestorage.app',
    iosBundleId: 'com.example.consulto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7SnYv-NUM3n2DAL-077lkrDxYsFhaE_Y',
    appId: '1:958917211661:web:aa1385d09faa8595a74744',
    messagingSenderId: '958917211661',
    projectId: 'consulto-3bd7b',
    authDomain: 'consulto-3bd7b.firebaseapp.com',
    storageBucket: 'consulto-3bd7b.firebasestorage.app',
    measurementId: 'G-F6BQ2PDBYQ',
  );

}